version: '3.1'

services:
  vue:
    build: Onlinecalculatorfrontend/
    image: musqueteers/onlinecalculatorfrontend
    restart: always
    ports: 
      - "80:80"
  django:
    build: Onlinecalculator/
    image: musqueteers/onlinecalculator
    restart: always
    ports: 
      - "8000:8000"